bid/urls.py
from django.urls import path

from . import views

app_name = "bid"

urlpatterns = [
    path("games/", views.GamesView.as_view(), name="games"),
    path("game/<int:pk>/", views.GameDetailView.as_view(), name="game_detail"),
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user"),
    path("game/create/", views.CreateGameView.as_view(), name="create_game"),
    path(
        "game/update/", views.UpdateGameWinnerView.as_view(), name="update_game_winner"
    ),
    path(
        "change_active_year/",
        views.ChangeActiveYearView.as_view(),
        name="change_active_year",
    ),
    path(
        "change_remainder/",
        views.ChangeRemainderView.as_view(),
        name="change_remainder",
    ),
]

iplBid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from bid import views

from .forms import LoginForm
from .views import ChangePasswordView, HomePageView, RegisterUserView, ResetPasswordView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bid/", include("bid.urls", namespace="bid")),
    path("", HomePageView.as_view(), name="home"),
    path("signup/", RegisterUserView.as_view(), name="signup"),
    path("password/reset/", ResetPasswordView.as_view(), name="password_reset"),
    path("password/change/", ChangePasswordView.as_view(), name="password_change"),
    path(
        "login/",
        LoginView.as_view(template_name="login.html", authentication_form=LoginForm),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(next_page="/"),
        name="logout",
        kwargs={"next_page": "/"},
    ),
    path("dream11/add_match/", views.AddMatchView.as_view(), name="add_match"),
    path("dream11/scores/", views.ScoresView.as_view(), name="scores"),
    path("dream11/add_player/", views.AddPlayerView.as_view(), name="add_player"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bid/views.py
import datetime
import os

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, View
from pytz import timezone

from bid.decorators import super_user_or_not
from bid.models import (
    ActiveYear,
    Dream11Matches,
    Dream11Scores,
    Game,
    Game_Result,
    UserProfile,
)
from iplBid.settings import ALL_TEAMS
from iplBid.settings import DREAM11_PLAYERS as players
from iplBid.settings import EMAIL_HOST_USER
from iplBid.settings import IPL_TEAMS as teams
from iplBid.settings import (
    MAXIMUM_BID_VALUE,
    MINIMUM_BID_VALUE,
    PLAYOFFS_MAXIMUM_BID_VALUE,
    PLAYOFFS_MINIMUM_BID_VALUE,
)

# Create your views here.


def remainder():
    users = UserProfile.objects.filter(year=int(os.environ["CURRENT_YEAR"]))
    today_date_start = datetime.datetime.now(timezone("Asia/Kolkata"))
    today_date_end = today_date_start + datetime.timedelta(hours=2)
    game = (
        Game.objects.filter(date__gt=today_date_start, date__lt=today_date_end)
        .order_by("date")
        .first()
    )
    if not game:
        print("No game found")
        return
    game_date = game.date.astimezone(timezone("Asia/Kolkata"))
    game_date = game_date - datetime.timedelta(minutes=1)
    for user in users:
        game_result = Game_Result.objects.filter(user=user, game=game)
        if not game_result:
            if not user.remainder:
                continue
            email = user.user.email
            print("email", email)
            send_mail(
                "Remainder for the upcoming match",
                f"""
                Hi {user.user.first_name},
                You have not placed a bid for the upcoming match between {game.team1} and {game.team2}.
                Please place a bid before {game_date.hour}:{game_date.minute}.
                Thank You""",
                EMAIL_HOST_USER,
                [email],
                fail_silently=False,
            )


@method_decorator(super_user_or_not, name="dispatch")
class AddPlayerView(CreateView):
    template_name = "bid/add_player.html"
    model = Dream11Scores
    fields = ["name"]
    success_url = "/dream11/add_player/"
    context_object_name = "form"


@method_decorator(super_user_or_not, name="dispatch")
class AddMatchView(View):
    template_name = "bid/add_match.html"

    def get(self, request):
        try:
            latestMatch = Dream11Matches.objects.latest("date")
            # get Games from the date of the latest match
            game = Game.objects.filter(date__gt=latestMatch.date).first()
        except Dream11Matches.DoesNotExist:
            latestMatch = None
            game = None
        return render(
            request,
            self.template_name,
            {"teams": teams, "players": players, "game": game},
        )

    def post(self, request):
        print(request.POST)
        if request.POST.get("cancelled") == "on":
            game = Game.objects.get(id=request.POST.get("gameId"))
            Dream11Matches.objects.create(game=game, isCancelled=True)
            return redirect(reverse("scores"))
        first = request.POST.get("first")
        second = request.POST.get("second")
        third = request.POST.get("third")
        fourth = request.POST.get("fourth")
        if request.POST.get("firstCheck") == "on":
            first = request.POST.get("firstText")
        if request.POST.get("secondCheck") == "on":
            second = request.POST.get("secondText")
        if request.POST.get("thirdCheck") == "on":
            third = request.POST.get("thirdText")
        if request.POST.get("fourthCheck") == "on":
            fourth = request.POST.get("fourthText")

        game = Game.objects.get(id=request.POST.get("gameId"))
        Dream11Matches.objects.create(
            game=game, first=first, second=second, third=third
        )
        return redirect(reverse("scores"))


@method_decorator(super_user_or_not, name="dispatch")
class ScoresView(View):
    template_name = "bid/scores.html"

    def get(self, request):
        scores = list(Dream11Scores.objects.all())
        scores.sort(key=lambda x: x.profit, reverse=True)
        # scores[0]['rgb'] = 'rgb(255, 215, 0)'
        # scores[1]['rgb'] = 'rgb(192, 192, 192)'
        # scores[2]['rgb'] = 'rgb(205, 127, 50)'
        matches = Dream11Matches.objects.all().order_by("-date")
        matches_paginator = Paginator(list(matches), 10)
        matches_games_page = matches_paginator.get_page(request.GET.get("page", 1))
        return render(
            request,
            self.template_name,
            {"scores": scores, "matches": matches_games_page},
        )


@method_decorator(super_user_or_not, name="dispatch")
class CreateGameView(View):
    template_name = "bid/create_game.html"

    def get(self, request):
        latestGameDate = Game.objects.latest("date").date
        latestGameDate = latestGameDate.astimezone(timezone("Asia/Kolkata"))
        print(latestGameDate.date(), latestGameDate.hour)
        if latestGameDate.hour == 19:
            latestGameDate = latestGameDate + datetime.timedelta(days=1)
            latestGameTime = "15:00:00"
        else:
            latestGameTime = "19:00:00"
        return render(
            request,
            self.template_name,
            {
                "teams": teams,
                "latestGameDate": latestGameDate.day,
                "latestGameMonth": latestGameDate.month,
                "latestGameTime": latestGameTime,
            },
        )

    def post(self, request):
        print(request.POST)
        if "isPlayOffs" in request.POST:
            isPlayOffs = True
        else:
            isPlayOffs = False
        date = f"{int(os.environ['CURRENT_YEAR'])}-{request.POST['month']}-{request.POST['date']}T{request.POST['time']}+05:30"
        Game.objects.create(
            date=date,
            team1=request.POST["team1"],
            team2=request.POST["team2"],
            isPlayOffs=isPlayOffs,
        )
        messages.success(request, "Game Created Successfully")
        if "add" in request.POST:
            return redirect(reverse("bid:create_game"))
        else:
            return redirect(reverse("bid:games") + "#upcoming")


@method_decorator(super_user_or_not, name="dispatch")
class UpdateGameWinnerView(View):
    template_name = "bid/update_game.html"

    def get(self, request):
        games = Game.objects.filter(completed=False).filter(
            date__lte=datetime.datetime.now(timezone("Asia/Kolkata"))
        )
        return render(request, self.template_name, {"games": games})

    def post(self, request):
        print(request.POST)
        game = Game.objects.get(id=request.POST["gameId"])
        if request.POST["team"] == "None":
            game.isCancelled = True
        game.winner = request.POST["team"]
        game.save()
        return redirect(reverse("bid:update_game_winner"))


class UserDetailView(LoginRequiredMixin, View):
    model = UserProfile
    template_name = "bid/user_detail.html"

    def get(self, request, *args, **kwargs):
        print(request.GET)
        status = request.GET.get("status")
        team = request.GET.get("team")
        if not status:
            status = "no"
        if not team:
            team = "no"

        current_year = str(request.user.active_year.year)
        user = UserProfile.objects.get(pk=kwargs["pk"])
        game_results = Game_Result.objects.filter(user=user, year=int(current_year))
        if status != "no":
            if status == "won":
                game_results = game_results.filter(won=True, completed=True)
            elif status == "lost":
                game_results = game_results.filter(
                    won=False, completed=True, cancelled=False
                )
            elif status == "cancelled":
                game_results = game_results.filter(cancelled=True)
            elif status == "not_completed":
                game_results = game_results.filter(completed=False)
            else:
                pass
        if team != "no":
            if team in ALL_TEAMS:
                game_results = game_results.filter(
                    game__team1=team
                ) | game_results.filter(game__team2=team)
            else:
                pass
        results_array = []
        for game_result in game_results:
            results_array.append(game_result)
        results_array.sort(key=lambda x: x.game.date, reverse=True)
        results_paginator = Paginator(list(results_array), 10)
        results_games_page = results_paginator.get_page(request.GET.get("page", 1))
        return render(
            request,
            self.template_name,
            {
                "results": results_games_page,
                "result_user": user,
                "teams": teams,
                "all_teams": ALL_TEAMS,
                "status": status,
                "team": team,
                "profile_pk": user.pk,
            },
        )


class ChangeActiveYearView(LoginRequiredMixin, View):
    model = ActiveYear

    def post(self, request):
        activeYear = ActiveYear.objects.get(user=request.user)
        activeYear.year = int(request.POST["year"])
        print("year", request.POST["year"])
        activeYear.save()
        print("path", request.POST["path"])
        if request.POST["path"] == "/bid/games/":
            return redirect(reverse("bid:games") + "#ongoing")
        if "/bid/user" in request.POST["path"]:
            return redirect(
                "/bid/user/"
                + str(
                    request.user.profiles.filter(year=int(activeYear.year)).first().id
                )
                + "?status=no&team=no"

bid/templates/bid/add_player.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
<h3>Add Player Page:</h3><br/>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" name="submit" value="Add" class="btn btn-primary">
    </form>
    <br><br>
{% endblock %}

bid/templates/bid/game_detail.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load customTags %}
{% load static %}
{% block content %}
<svg onclick="goBack();" xmlns="http://www.w3.org/2000/svg" width="30px" height="30px" fill="currentColor" class="bi bi-arrow-left-square-fill" viewBox="0 0 16 16">
    <path d="M16 14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12zm-4.5-6.5H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5a.5.5 0 0 0 0-1z"/>
  </svg>
<br/>
<br/>
<h2><span {% if game.winner %}style="color:{% if game.winner == game.team1 %}green{% else %}red{% endif %}"{% endif %}><img style="width: 50px; height: 50px;" src="{% static 'bid/img/' %}{{ game.team1 }}.png" alt="Italian Trulli"> {{ game.team1 }}</span> vs <span {% if game.winner %}style="color:{% if game.winner == game.team2 %}green{% else %}red{% endif %}"{% endif %}><img style="width: 50px; height: 50px" src="{% static 'bid/img/' %}{{ game.team2 }}.png" alt="Italian Trulli"> {{ game.team2 }} </span>{% if game.isPlayOffs %}<span> (Playoffs)</span>{% endif %}</h2>
{% if game|checkPlayOffsCondition:user %}
<table class="table table-striped contents" style="font-size:80%;text-align:left;">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Team</th>
        <th scope="col">Bid Amount</th>
        <th scope="col">Status</th>
        {% if user.is_superuser %}
            <th scope="col"></th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for obj in listObj %}
        <tr>
            <td><a href="{% url 'bid:user' obj.user.pk %}?status=no&team=no">{{ obj.name }}</a></td>
            <td><span>{{ obj.team }}</span></td>
            <td>{{ obj.amount }}</td>
            {% if obj.did_not_bid %}
                {% if not obj.isCancelled %}
                    <td style="color: red">No Bid</td>
                {% else %}
                    <td style="color: orange">Cancelled (No Bid)</td>
                {% endif %}
                {% if user.is_superuser %}
                    {% if not game.completed %}
                        <td><a class="btn btn-primary" style="font-size:65%" data-toggle="modal" data-target="#exampleModal" data-whatever=",{{ game.team1 }},{{ game.team2 }},{{ game.pk }},other_create,{{ obj.user.pk }},{% if game.isPlayOffs %}{{ playoffs_min_bid }},{{ playoffs_max_bid }}{% else %}{{ min_bid }},{{ max_bid }}{% endif %}" href="#" role="button">BID AMOUNT</a></td>
                    {% endif %}
                {% endif %}
            {% else %}
                {% if game.completed %}
                    {% if not obj.isCancelled %}
                        {% if obj.won %}
                            <td style="color:green">Won</td>
                        {% else %}
                            <td style="color:red">Lost</td>
                        {% endif %}
                    {% else %}
                        <td style="color:orange">Cancelled</td>
                    {% endif %}
                {% else %}
                    <td>Not Decided</td>
                {% endif %}
                {% if user.is_superuser %}
                    {% if not game.completed %}
                        <td><a class="btn btn-primary" style="font-size:65%" data-toggle="modal" data-target="#exampleModal" data-whatever="{{ obj.amount }},{{ game.team1 }},{{ game.team2 }},{{ game.pk }},other_update,{{ obj.user.pk }},{% if game.isPlayOffs %}{{ playoffs_min_bid }},{{ playoffs_max_bid }}{% else %}{{ min_bid }},{{ max_bid }},{{ obj.team }}{% endif %}" href="#" role="button">UPDATE BID</a></td>
                    {% endif %}
                {% endif %}
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h6>Bids are not visible until the game is completed!</h6>
{% endif %}
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New message</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
            
          </button>
        </div>
        <div class="modal-body">
          <form class="form-container" action="{% url 'bid:games' %}" method="POST" enctype="multipart/form-data" id="bid_form">
            {% csrf_token %}
            <div class="form-group">
              <label for="team" class="col-form-label">Team:</label>
              <select name="team" class="form-select" id="team" required>
              </select>
              
            </div>
            <div class="form-group">
              <label for="amount" class="col-form-label">Bid Amount:</label>
              <input name="amount" type="number" min="{{ min_bid }}" max="{{ max_bid }}" class="form-control" id="amount" required>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
    <script>
        $('#exampleModal').on('show.bs.modal', function (event) {
            const button = $(event.relatedTarget) // Button that triggered the modal
            const recipient = button.data('whatever') // Extract info from data-* attributes
            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
            console.log("recipient", recipient)
            const amount = recipient.split(",")[0]
            const team1 = recipient.split(",")[1]
            const team2 = recipient.split(",")[2]
            const gameId = recipient.split(",")[3]
            const method = recipient.split(",")[4]
            const pk = recipient.split(",")[5]
            const min_bid = recipient.split(",")[6]
            const max_bid = recipient.split(",")[7]
            const team = recipient.split(",")[8]
            const select = document.getElementById('team');
            const options = document.querySelectorAll('#team option');
            options.forEach(o => o.remove());
            select.options[select.options.length] = new Option(team1, team1);
            select.options[select.options.length] = new Option(team2, team2);
            if (team1 === team) {
                select.value = team1;
            } else if (team2 === team) {
                select.value = team2;
            }
            else {
                select.value = "";
            }
            amount_field = document.getElementById('amount')
            amount_field.value = amount
            amount_field.min = parseInt(min_bid)
            amount_field.max = parseInt(max_bid)
            const bid_form = document.getElementById("bid_form");
            // create an input field to insert
            const gameIdField = document.createElement("input");
            const methodField = document.createElement("input");
            const pkField = document.createElement("input");
            // set input field data type to text
            gameIdField.setAttribute("type", "hidden");
            methodField.setAttribute("type", "hidden");
            pkField.setAttribute("type", "hidden");
            // set input field name 
            gameIdField.setAttribute("name", "gameId");
            gameIdField.value = gameId;
            methodField.setAttribute("name", "method");
            methodField.value = method;
            pkField.setAttribute("name", "user_pk");
            pkField.value = pk;
            // select last position to insert element before it
            const pos = bid_form.childElementCount;

            // insert element
            bid_form.insertBefore(gameIdField, bid_form.childNodes[pos]);
            bid_form.insertBefore(methodField, bid_form.childNodes[pos+1]);
            bid_form.insertBefore(pkField, bid_form.childNodes[pos+2]);
          })
        const goBack = () => {
            window.history.back();
        }
    </script>
{% endblock script %}

bid/templates/bid/user_detail.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load customTags %}
{% block content %}
    <svg onclick="goBack();" xmlns="http://www.w3.org/2000/svg" width="30px" height="30px" fill="currentColor" class="bi bi-arrow-left-square-fill" viewBox="0 0 16 16">
        <path d="M16 14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12zm-4.5-6.5H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5a.5.5 0 0 0 0-1z"/>
    </svg>
    <br/>
    <br/>
    <h2>{{ result_user.user.first_name.capitalize }}'s Bid History</h2>
    <h5>Amount: {{ result_user.amount }}</h5>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Stats
      </button>
      
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">{{ result_user.user.first_name.capitalize }}'s Chart</h5>
              <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
                
              </button>
            </div>
            <div class="modal-body">
                <canvas id="myChart" width="400" height="400"></canvas>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <div class="filter-container">
        <div class="flex-1">
            <label for="status" class="form-label">Status:</label>
            <select id="status-field" name="status" class="form-select" aria-label="Default select example" onchange="changeParams();" style="font-size: 75%">
                <option value="no">No Filter</option>
                <option value="won">Won</option>
                <option value="lost">Lost</option>
                <option value="not_completed">Not Completed</option>
                <option value="cancelled">Cancelled</option>
            </select>
        </div>
        <div class="flex-2">
            <label for="team" class="form-label">Team:</label>
            <select id="team-field" name="year" class="form-select" aria-label="Default select example" onchange="changeParams();" style="font-size: 75%">
                <option value="no">No Filter</option>
                {% for team in teams %}
                    <option value="{{ team.0 }}">{{ team.1 }}</option>
                {% endfor %}
            </select>
        </div>
      </div>
    </br>
    <table class="table table-striped contents" style="font-size:80%;text-align:left;">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Team</th>
            <th scope="col">Bid</th>
            <th scope="col">Status</th>
            <th scope="col">Result</th>
        </tr>
        </thead>
        <tbody>
        {% for result in results %}
            <tr>
                <td><a href="{% url 'bid:game_detail' result.game.pk %}">{{ result.game.name }}</a>{% if result.game.isPlayOffs %}<span> (Playoffs) </span>{% endif %}</td>
                {% if result.game|checkPlayOffsCondition:user or result_user.pk == user.pk %}<td>{{ result.team }}</td>{% else %}<td>Can't Disclose</td>{% endif %}
                {% if result.game|checkPlayOffsCondition:user or result_user.pk == user.pk %}<td>{{ result.bid_amount }}</td>{% else %}<td>Can't Disclose</td>{% endif %}
                {% if result.did_not_bid %}
                    {% if not result.cancelled %}
                        <td style="color: red">-{{ result.bid_amount }}</td>
                    {% else %}
                        <td style="color: orange">-{{ result.bid_amount }} (NO Bid)</td>
                    {% endif %}
                {% else %}
                    {% if result.game.completed %}
                        {% if result.won %}
                            <td style="color: green">+{{ result.bid_amount }}</td>
                        {% elif result.cancelled %}
                            <td style="color: orange">N/A</td>
                        {% else %}
                            <td style="color: red">-{{ result.bid_amount }}</td>
                        {% endif %}
                    {% else %}
                        <td>Not Decided</td>
                    {% endif %}
                {% endif %}
                {% if result.completed %}
                    {% if not result.cancelled %}
                        {% if result.won %}
                            <td style="color:green">Won</td>
                        {% elif result.did_not_bid %}
                            <td style="color:red">No Bid</td>
                        {% else %}
                            <td style="color:red">Lost</td>
                        {% endif %}
                    {% else %}
                        <td style="color:orange">Cancelled</td>
                    {% endif %}
                {% else %}
                    <td>N/A</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination" id="pagination">
        <nav aria-label="...">
            <ul class="pagination">
              
            <li class="page-item {% if not results.has_previous %} disabled {% endif %}">
                <a class="page-link" href="?status={{ status }}&team={{ team }}&page={% if results.has_previous %}{{ results.previous_page_number }}{% endif %}">Previous</a>
            </li>
              <li class="page-item {% if not results.has_next %} disabled {% endif %}">
                <a class="page-link" href="?status={{ status }}&team={{ team }}&page={% if results.has_next %}{{ results.next_page_number }}{% endif %}">Next</a>
              </li>
            </ul>
          </nav>
    </div>
    <br/>
    <br/>
{% endblock %}

{% block script %}
<script>
    const ctx = document.getElementById('myChart').getContext('2d');
    const all_teams = JSON.parse('{{ all_teams|convertToJson }}')
    const myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: {{ result_user.chart.0|safe }},
            datasets: [{
                label: 'Amount',
                data: {{ result_user.chart.1|safe }},
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
    const changeParams = () => {
        const status = document.getElementById('status-field').value;
        const team = document.getElementById('team-field').value;
        window.location.href = `{% url 'bid:user' profile_pk %}?status=${status}&team=${team}`;
    }
    window.addEventListener('DOMContentLoaded', function() {
        const urlParams = new URLSearchParams(window.location.search);
        const statusField = document.getElementById('status-field');
        const teamField = document.getElementById('team-field');
        
        // Get the value from the URL parameter 'value'
        const status = urlParams.get('status');
        const team = urlParams.get('team');
        console.log("status", status);
        console.log("team", team);

        if (status) {
            if (status == "won") {
                statusField.value = "won";
            }
            else if (status == "lost") {
                statusField.value = "lost";
            }
            else if (status == "cancelled") {
                statusField.value = "cancelled";
            }
            else if (status == "not_completed") {
                statusField.value = "not_completed";
            }
            else {
                statusField.value = "no";
            }
        }
        else {
            statusField.value = "no";
        }
        if (team) {
            if (all_teams.includes(team)) {
                teamField.value = team;
            }
            else {
                teamField.value = "no";
            }
        }
        else {
            teamField.value = "no";
        }
        
      });
    const goBack = () => {
        window.history.back();
    }
    </script>
{% endblock script %}
{% block style %}
    <style>
        .filter-container {
            display: flex;
            margin-left: 30%;
        }
        .flex-1 {
            flex: 1;
            padding-left: 10px;
        }
        .flex-2 {
            flex: 0.8;
            padding-left: 10px;
        }
    </style>
{% endblock %}   