bid/urls.py
from django.urls import path

from . import views

app_name = "bid"

urlpatterns = [
    path("games/", views.GamesView.as_view(), name="games"),
    path("game/<int:pk>/", views.GameDetailView.as_view(), name="game_detail"),
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user"),
    path("game/create/", views.CreateGameView.as_view(), name="create_game"),
    path(
        "game/update/", views.UpdateGameWinnerView.as_view(), name="update_game_winner"
    ),
    path(
        "change_active_year/",
        views.ChangeActiveYearView.as_view(),
        name="change_active_year",
    ),
    path(
        "change_remainder/",
        views.ChangeRemainderView.as_view(),
        name="change_remainder",
    ),
]

iplBid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from bid import views

from .forms import LoginForm
from .views import ChangePasswordView, HomePageView, RegisterUserView, ResetPasswordView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bid/", include("bid.urls", namespace="bid")),
    path("", HomePageView.as_view(), name="home"),
    path("signup/", RegisterUserView.as_view(), name="signup"),
    path("password/reset/", ResetPasswordView.as_view(), name="password_reset"),
    path("password/change/", ChangePasswordView.as_view(), name="password_change"),
    path(
        "login/",
        LoginView.as_view(template_name="login.html", authentication_form=LoginForm),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(next_page="/"),
        name="logout",
        kwargs={"next_page": "/"},
    ),
    path("dream11/add_match/", views.AddMatchView.as_view(), name="add_match"),
    path("dream11/scores/", views.ScoresView.as_view(), name="scores"),
    path("dream11/add_player/", views.AddPlayerView.as_view(), name="add_player"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{% load customTags %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <title>IPL Bid</title>
        <link rel = "icon" href = "{% static 'bid/img/logo.png' %}" type = "image/x-icon">
        <style>
            body {font-family: Arial, Helvetica, sans-serif;}
            
            * {box-sizing: border-box;}

            .topnav {
              overflow: hidden;
              background-color: #333;
            }

            .topnav a {
              float: left;
              display: block;
              color: #f2f2f2;
              text-align: center;
              padding: 14px 16px;
              text-decoration: none;
              font-size: 17px;
            }

            .topnav a:hover {
              background-color: #ddd;
              color: black;
            }

            .topnav a.active {
              background-color: #04AA6D;
              color: white;
            }

            .topnav .icon {
              display: none;
            }

            @media screen and (max-width: 600px) {
              .topnav a:not(:first-child) {display: none;}
              .topnav a.icon {
                float: right;
                display: block;
              }
            }

            @media screen and (max-width: 600px) {
              .topnav.responsive {position: relative;}
              .topnav.responsive .icon {
                position: absolute;
                right: 0;
                top: 0;
              }
              .topnav.responsive a {
                float: none;
                display: block;
                text-align: left;
              }
            }
        </style>
        {% block style %}

        {% endblock %}
    </head>
    <body>
      {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin-left:5%; margin-right:5%">
            {{ message }}
            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
      {% endif %}
        <div class="topnav" id="myTopnav">
          <a href="/" class="active">Home</a>
          <a href="{% url 'bid:games' %}#ongoing">Games</a>
          {% if user.is_superuser %}
              <a href="/admin">Admin</a>
              <a href="{% url 'bid:create_game' %}">Create Games</a>
              <a href="{% url 'bid:update_game_winner' %}">Update Game Winners</a>
              <a href="{% url 'add_player' %}">Add Player</a>
              <a href="{% url 'add_match' %}">Add Match</a>
              <a href="{% url 'scores' %}">Dream11 Scoresheet</a>
          {% endif %}
          {% if user.is_authenticated %}
              {% if user.username|usernameCheck %}
                <a href="{% url 'scores' %}">Dream11 Scoresheet</a>
              {% endif %}
              <a href="{% url 'password_change' %}">Change Password</a>
              <a href="{% url 'logout' %}">Log Out</a>
          {% else %}
              <a href="{% url 'password_reset' %}">Reset Password</a>
              <a class="nav navbar-right" href="{% url 'login' %}"><span class="glyphicon glyphicon-user">Login</span></a>
              <a class="nav navbar-right" href="{% url 'signup' %}"><span class="glyphicon glyphicon-user">SignUp</span></a>
          {% endif %}
          <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
          </a>
        </div>
        <br>
          {% if request.path == '/' or '/bid/games' in request.path or '/bid/user' in request.path %}
        <form id="change-year-form" method="POST" action="{% url 'bid:change_active_year' %}">
          {% csrf_token %}
            <input type="hidden", value={{ request.path }} name="path">
            <select id="year-select" name="year" class="form-select" aria-label="Default select example" style="margin-left: 5%; width: 60vw" onchange="changeYear()">
              <option {% if user.active_year.year == 2025 %} selected {% endif %} value="2025">Current Year (2025)</option>
              <option {% if user.active_year.year == 2024 %} selected {% endif %} value="2024">2024</option>
              <option {% if user.active_year.year == 2023 %} selected {% endif %}value="2023">2023</option>
              <option {% if user.active_year.year == 2022 %} selected {% endif %}value="2022">2022</option>
            </select>
        </form>
          {% endif %}
        <br>
        <br>
        <div class="content container">
            {% block content %}

            {% endblock %}
        </div>
        <script>
          function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
            function myFunction() {
              var x = document.getElementById("myTopnav");
              if (x.className === "topnav") {
                x.className += " responsive";
              } else {
                x.className = "topnav";
              }
            }
            const changeYear = function() {
              document.getElementById('change-year-form').submit();
            }
            const changeRemainder = function() {
              document.getElementById('change-remainder').submit();
            }
        </script>
        {% block script %}
        {% endblock %}
    </body>
</html>

templates/change_password.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
{% if email %}
<h3>Password Reset:</h3><br/>
{% else %}
<h3>Change Password:</h3><br/>
{% endif %}
<form method="POST" action="{% if email %}{% url 'password_reset' %}{% else %}{% url 'password_change' %}{% endif %}">
    {% csrf_token %}
    <input type="hidden" name="email" value="{{email}}">
    <input type="hidden" name="username" value="{{username}}">
    <input type="hidden" name="userId" value="{{userId}}">
    <div class="form-group">
      <label>Password</label>
      <input type="password" name="password1" class="form-control" placeholder="Enter New Password">
    </div>
    <div class="form-group">
      <label>Confirm Password</label>
      <input type="password" name="password2" class="form-control" placeholder="Confirm New Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block content %}
    <h2>LeaderBoard</h2>
    <table class="table table-striped contents" style="font-size:65%;text-align:left;overflow: scroll;">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Amount</th>
            <th scope="col">Won</th>
            <th scope="col">Lost</th>
            <th scope="col">Win Percentage</th>
        </tr>
        </thead>
        <tbody>
        {% for current_user in users %}
            <tr {% if current_user.user.pk == user.pk %} style="background:rgb(237, 209, 237)" {% endif %}>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'bid:user' current_user.pk %}?status=no&team=no">{{ current_user.user.first_name.upper }} {{ current_user.user.last_name.upper }}</a></td>
                <td>{{ current_user.amount }}</td> 
                <td>{{ current_user.stats.0 }}</td> 
                <td>{{ current_user.stats.1 }}</td> 
                <td {% if current_user.win_percentage < 50 %} style="color:red" {% else %} style="color:green" {% endif %}>{{ current_user.win_percentage }}%</td> 
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
<h3>Login:</h3><br/>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <span class="psw">Forgot password? <a href="{% url 'password_reset' %}">Reset here</a></span>
        <br/><br/>
        <input type="submit" name="submit" value="Login" class="btn btn-primary">
    </form>
    <br><br>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
<h3>Sign Up Page:</h3><br/>
    {% if not "localhost" in request.META.HTTP_HOST %}
        <h5> Sorry for the inconvenience, but the registration is currently closed. </h5>
    {% else %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" name="submit" value="Register" class="btn btn-primary">

        </form>
    {% endif %}
    <br><br>
{% endblock %}

templates/reset_password.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<h3>Password Reset:</h3><br/>
<form method="POST" action="{% url 'password_reset' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Registered Email">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}